name: Docker Image CI

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.36.0
              id: packageVersion
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                WITH_V: true
                DEFAULT_BUMP: patch
                RELEASE_BRANCHES: main
                
            - name: Show package.json info
              run: |
                echo new_tag:${{ steps.packageVersion.outputs.new_tag }}
                echo tag:${{ steps.packageVersion.outputs.tag }}
                echo part:${{ steps.packageVersion.outputs.part }}

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-template:${{ steps.packageVersion.outputs.new_tag }}
