name: Docker Image CI

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v3
              id: semantic
              with:
                semantic_version: 16
                # you can set branches for semantic-release above v16.
                branches: main
                extra_plugins: |
                  @semantic-release/changelog@3.0.0
                  @semantic-release/git
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                
            - name: Do something when a new release published
              run: |
                echo new_release_version:${{ steps.semantic.outputs.new_release_version }}
                echo new_release_major_version:${{ steps.semantic.outputs.new_release_major_version }}
                echo new_release_minor_version:${{ steps.semantic.outputs.new_release_minor_version }}
                echo new_release_patch_version:${{ steps.semantic.outputs.new_release_patch_version }}

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-template:${{ steps.semantic.outputs.new_release_version }}
