name: Docker Image CI

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Semantic Release
                uses: cycjimmy/semantic-release-action@v3
                id: semantic   # Need an `id` for output variables
                env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                
            - name: Do something when a new release published
                if: steps.semantic.outputs.new_release_published == 'true'
                run: |
                echo ${{ steps.semantic.outputs.new_release_version }}
                echo ${{ steps.semantic.outputs.new_release_major_version }}
                echo ${{ steps.semantic.outputs.new_release_minor_version }}
                echo ${{ steps.semantic.outputs.new_release_patch_version }}

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-template:${{ steps.semantic.outputs.new_release_version }}